name: Deploy Website On Push

on:
  push:
    branches: [ "master" ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Get Latest Code
      uses: actions/checkout@v4

    - name: Sync Files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.magnapartner.com
        username: ${{ secrets.CICD_EMAIL}}
        password: ${{ secrets.CICD_PASSWORD }}
        server-dir: /
