name: Deploy Website On Push

on:
  push:
    branches: [ "master" ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Get Latest Code
      uses: actions/checkout@v3

    - name: Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ftp.magnapartner.com
        remote-user: ${{ secrets.CICD_EMAIL }}
        private-ssh-key: ${{ secrets.SSH_KEY }}
        destination-path: /
